image: node:8.15.1

pipelines:
  default:
    - step:
        name: Build application
        script:
          - npm install -g ionic
          - npm install
          - ionic build
  branches:
    master:
      - step:
          name: Package application
          script:
            - npm install -g ionic
            - npm install
            - ionic build --prod
            - mkdir deployment_package
            - cp -r node_modules deployment_package
            - cp -r src deployment_package
            - cp -r www deployment_package
            - cp *.json deployment_package
            - cp server.js deployment_package
            - tar czf effective-giving.tar.gz deployment_package
          artifacts:
            - effective-giving.tar.gz
      - step:
          name: Deploy to test environment
          deployment: test
          script:
            - pipe: atlassian/heroku-deploy:0.1.1
              variables:
                HEROKU_API_KEY: '558b852a-56d6-492d-8c57-a277964b673a'
                HEROKU_APP_NAME: 'effective-giving'
                ZIP_FILE: 'effective-giving.tar.gz'
                DEBUG: 'true'
